### ISSUE TITLE
"Transparent" background color instead of color 0

### ISSUE THREAD

**Issue by Cynosphere** [okibcn/nano-for-windows#8]
Would it be possible to have the background color be "transparent" so it uses the terminal's defined background color instead of defaulting to color 0? I use color 0 as a background color other places in nano (line numbers, scrollbar, 80 col marker). If its a limitation of PDCursesMod, then I guess I'll just cope with using it through WSL or something...

**Comment by okibcn** [comment]
No, it's not a limitation of PDCursesMod. It is an artifact of using nano sources with PDCursesMod that supports truecolor. It is fixable as soon as I have time to look into it.

**Comment by okibcn** [comment]
Solved in **[nano v7.2-9-10164.3](https://github.com/okibcn/nano-for-windows/releases/tag/v7.2-9-10164.3)**.
